#include "draw.h"
#include "gba.h"
#include "images.h"

// TA-TODO: Include any header files for images generated by nin10kit.
// Example for the provided garbage image:
// #include "images/garbage.h"

// TA-TODO: Add any draw/undraw functions for sub-elements of your app here.
// For example, for a snake game, you could have a drawSnake function
// or a drawFood function
//
// e.g.:
// static void drawSnake(Snake* snake);
// static void drawFood(Food* food);

// This function will be used to draw everything about the app
// including the background and whatnot.
void fullDrawAppState(AppState *state) {
    drawFullScreenImageDMA(game);
    drawImageDMA(state->player.x, state->player.y, PLAYER_WIDTH, PLAYER_HEIGHT, player);
    drawRectDMA(state->rocket.x, state->rocket.y, ROCKET_WIDTH, ROCKET_HEIGHT, RED);
    drawChar(LIVES_X, LIVES_Y, state->lives, BLACK);
}

// This function will be used to undraw (i.e. erase) things that might
// move in a frame. E.g. in a Snake game, erase the Snake, the food & the score.
void undrawAppState(AppState *state) {
    drawPartBackground(state->player.x, state->player.y, PLAYER_WIDTH, PLAYER_HEIGHT, game);
    drawPartBackground(state->rocket.x, state->rocket.y, ROCKET_WIDTH, ROCKET_HEIGHT,
                game);
    drawPartBackground(LIVES_X, LIVES_Y, 6, 8, game);
}

// This function will be used to draw things that might have moved in a frame.
// For example, in a Snake game, draw the snake, the food, the score.
void drawAppState(AppState *state) {
    drawImageDMA(state->player.x, state->player.y, PLAYER_WIDTH, PLAYER_HEIGHT,
                player);
    drawRectDMA(state->rocket.x, state->rocket.y, ROCKET_WIDTH, ROCKET_HEIGHT,
                RED);
    drawChar(LIVES_X, LIVES_Y, state->lives, BLACK);
}
